controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    steering_position_controller:
      type: position_controllers/JointGroupPositionController
    suspension_position_controller:
      type: position_controllers/JointGroupPositionController

wheel_velocity_controller:
  ros__parameters:
    joints:
      - back_wheel_L_joint
      - back_wheel_R_joint
      - front_wheel_L_joint
      - front_wheel_R_joint
      - middle_wheel_L_joint
      - middle_wheel_R_joint

steering_position_controller:
  ros__parameters:
    joints:
      - suspension_steer_B_L_joint
      - suspension_steer_B_R_joint
      - suspension_steer_F_L_joint
      - suspension_steer_F_R_joint

suspension_position_controller:
  ros__parameters:
    joints:
      - suspension_arm_B2_L_joint
      - suspension_arm_B2_R_joint
      - suspension_arm_B_L_joint
      - suspension_arm_B_R_joint
      - suspension_arm_F_L_joint
      - suspension_arm_F_R_joint


